# Generated by Django 4.2.1 on 2023-05-19 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indication', models.TextField(help_text='write indication...')),
                ('dosage', models.TextField()),
                ('preparation', models.TextField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medicinemodel')),
            ],
            options={
                'verbose_name': 'Medicine Detail',
                'verbose_name_plural': 'Medicine Details',
                'db_table': 'medicine_details',
            },
        ),
    ]
