# Generated by Django 4.2.1 on 2023-05-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('group', models.CharField(max_length=30)),
                ('trade_name', models.CharField(max_length=30)),
                ('price', models.PositiveSmallIntegerField()),
                ('mg', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='picture/uploads/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'db_table': 'medicine',
            },
        ),
    ]
